CREATE TABLE "CARS" (
	"COLOR"	TEXT NOT NULL,
	"MODEL"	TEXT NOT NULL,
	"BRAND"	TEXT NOT NULL,
	"AMOUNT" INTEGER NOT NULL UNIQUE
);

INSERT INTO CARS
VALUES('Red','FORTE','KIA',10);
INSERT INTO CARS
VALUES('BLACK','OCTAVIA','SKODA',52);
INSERT INTO CARS
VALUES('BLUE','YARIS','TOYOTA',23);

SELECT * FROM CARS ORDER BY AMOUNT ASC