CREATE TABLE "BEVERAGES" (
	"DRINKS" TEXT NOT NULL,
	"VOL" INTEGER NOT NULL UNIQUE
);
INSERT INTO BEVERAGES
VALUES('LIKER',100);
INSERT INTO BEVERAGES
VALUES('VODKA',75);
INSERT INTO BEVERAGES
VALUES('GIN',50);
INSERT INTO BEVERAGES
VALUES('WHISKEY',25);

SELECT * FROM BEVERAGES WHERE VOL > (SELECT avg(VOL) FROM BEVERAGES)