CREATE TABLE "FLIGHTS" (
	"DESTINATION"	TEXT NOT NULL,
	"DATE"	TEXT NOT NULL,
	"FLIGHT_ID"	INTEGER,
	PRIMARY KEY("FLIGHT_ID")
);

CREATE TABLE "AIRPLANES" (
	"MODEL"	TEXT NOT NULL,
	"AIRPLANE_ID"	INTEGER,
	PRIMARY KEY("AIRPLANE_ID")
);



INSERT into AIRPLANES
VALUES ('RYANAIR 500',1)

INSERT into AIRPLANES
VALUES ('WIZAIR 600',2)


INSERT into AIRPLANES
VALUES ('ELAL 200',3)

INSERT into AIRPLANES
VALUES ('Qatar Airways 700',4)
INSERT into AIRPLANES
VALUES ('Emirates 600',5)
INSERT into AIRPLANES
VALUES ('EVA Air 300',6)

INSERT into AIRPLANES
VALUES ('Cathay Pacific Airways 400',7)

INSERT into AIRPLANES
VALUES ('Hainan Airlines 200',7)

INSERT into AIRPLANES
VALUES ('ATLAS Airlines 200',8)

INSERT into AIRPLANES
VALUES ('BERLAS Airlines 500',9)

INSERT into FLIGHTS
VALUES ('MAROCO','29/01/2022',1)
INSERT into FLIGHTS
VALUES ('NEW YORK','25/01/2022',2)
INSERT into FLIGHTS
VALUES ('MEXICO','26/01/2022',3)
INSERT into FLIGHTS
VALUES ('DUBAI','25/01/2022',4)
INSERT into FLIGHTS
VALUES ('ALASKA','06/01/2022',5)
INSERT into FLIGHTS
VALUES ('TEL AVIV','05/01/2022',6)
INSERT into FLIGHTS
VALUES ('GERMANY','16/01/2022'7)
INSERT into FLIGHTS
VALUES ('INDIA','15/01/2022',8)
INSERT into FLIGHTS
VALUES ('GREECE','20/01/2022',9)
INSERT into FLIGHTS
VALUES ('ITALIE','09/01/2022',10)
INSERT into FLIGHTS
VALUES ('EILAT','20/01/2022',11)



SELECT FLIGHT_ID,FLIGHTS.DATE,dest,AIRPLANES.TYPE FROM FLIGHTS JOIN AIRPLANES ON FLIGHT_ID = AIRPLANE_ID WHERE FLIGHT_ID < 11